### ISSUE TITLE
Does it support capture from GLSurfaceView?

### ISSUE THREAD

**Issue by Rich2020** [BeUni/ScreenShot#1]
For instance, from an Augmented Reality app: [HelloAR Demo app](https://developers.google.com/ar/develop/java/quickstart)

**Comment by shivams1011** [comment]
@Rich2020  Right now no support for GLSurfaceView, In the next release, I will make sure this will resolve.
Thanks for report issue

**Comment by Rich2020** [comment]
@shivams1011 Awesome, thanks!
